[package]
name = "com_calindora_follow"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0.68"
config = "0.13.3"
dotenvy = "0.15.6"
futures = "0.3.25"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", features = ["serde_derive"] }
sqlx = { version = "0.6.2", features = ["offline", "postgres", "runtime-actix-rustls", "uuid"] }
thiserror = "1.0.38"
tracing = { version = "0.1.37", features = ["log"] }
tracing-actix-web = "0.7.2"
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.2.2", features = ["serde"] }

[dev-dependencies]
once_cell = "1.17.0"
reqwest = "0.11.14"
