[package]
name = "com_calindora_follow"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
actix-web-validator = "5.0.1"
anyhow = "1.0.86"
bigdecimal = { version = "0.3.1", features = ["serde"] }
config = { git = "https://github.com/mehcode/config-rs.git", rev = "e3c1d0b452639478662a44f15ef6d5b6d969bf9b" }
dotenvy = "0.15.7"
futures = "0.3.30"
hex = "0.4.3"
hmac = "0.12.1"
once_cell = "1.19.0"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.117"
sha2 = "0.10.6"
sqlx = { version = "0.7", features = ["bigdecimal", "postgres", "runtime-tokio", "time", "tls-rustls", "uuid"] }
tera = "1.20.0"
thiserror = "1.0.61"
time = { version = "0.3.36", features = ["serde-human-readable", "macros"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-actix-web = "0.7.11"
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.8.0", features = ["serde"] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
reqwest = "0.12.5"
