[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 3171872035 } # 0xbd0eed23
]

[advisories]
ignore = [
    "RUSTSEC-2024-0370", # actix-web-validator
    "RUSTSEC-2024-0421", # actix-web-validator
]
