[advisories]
ignore = [
  { id = "RUSTSEC-2026-0173", reason = "proc-macro-erro2 is a transitive dependency through validator_derive. It should be replaced whenever validator_derive makes its next release." },
]

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]

[bans]
multiple-versions = "allow"
